export const escalasData = [
  { id: 1, nome: "Dó Maior", tipo: "Arpejos", status: "estudar" },
  { id: 2, nome: "Sol Maior", tipo: "Arpejos", status: "estudar" },
  { id: 3, nome: "Ré Maior", tipo: "Arpejos", status: "estudar" },
  { id: 4, nome: "Lá Maior", tipo: "Arpejos", status: "estudar" },
  { id: 5, nome: "Mi Maior", tipo: "Arpejos", status: "estudar" },
  { id: 6, nome: "Si Maior", tipo: "Arpejos", status: "estudar" },
  { id: 7, nome: "Fá # Maior", tipo: "Arpejos", status: "estudar" },
  { id: 8, nome: "Dó # Maior", tipo: "Arpejos", status: "estudar" },
  { id: 9, nome: "Fá Maior", tipo: "Arpejos", status: "estudar" },
  { id: 10, nome: "Si b Maior", tipo: "Arpejos", status: "estudar" },
  { id: 11, nome: "Mi b Maior", tipo: "Arpejos", status: "estudar" },
  { id: 12, nome: "Lá b Maior", tipo: "Arpejos", status: "estudar" },
  { id: 13, nome: "Ré b Maior", tipo: "Arpejos", status: "estudar" },
  { id: 14, nome: "Sol b Maior", tipo: "Arpejos", status: "estudar" },
  { id: 15, nome: "Dó b Maior", tipo: "Arpejos", status: "estudar" },
  { id: 16, nome: "lá menor", tipo: "Arpejos", status: "estudar" },
  { id: 17, nome: "mi menor", tipo: "Arpejos", status: "estudar" },
  { id: 18, nome: "si menor", tipo: "Arpejos", status: "estudar" },
  { id: 19, nome: "fá # menor", tipo: "Arpejos", status: "estudar" },
  { id: 20, nome: "dó # menor", tipo: "Arpejos", status: "estudar" },
  { id: 21, nome: "sol # menor", tipo: "Arpejos", status: "estudar" },
  { id: 22, nome: "ré # menor", tipo: "Arpejos", status: "estudar" },
  { id: 23, nome: "lá # menor", tipo: "Arpejos", status: "estudar" },
  { id: 24, nome: "ré menor", tipo: "Arpejos", status: "estudar" },
  { id: 25, nome: "sol menor", tipo: "Arpejos", status: "estudar" },
  { id: 26, nome: "dó menor", tipo: "Arpejos", status: "estudar" },
  { id: 27, nome: "fá menor", tipo: "Arpejos", status: "estudar" },
  { id: 28, nome: "si b menor", tipo: "Arpejos", status: "estudar" },
  { id: 29, nome: "mi b menor", tipo: "Arpejos", status: "estudar" },
  { id: 30, nome: "lá b menor", tipo: "Arpejos", status: "estudar" },
  { id: 31, nome: "Dó Maior", tipo: "Acordes", status: "estudar" },
  { id: 32, nome: "Sol Maior", tipo: "Acordes", status: "estudar" },
  { id: 33, nome: "Ré Maior", tipo: "Acordes", status: "estudar" },
  { id: 34, nome: "Lá Maior", tipo: "Acordes", status: "estudar" },
  { id: 35, nome: "Mi Maior", tipo: "Acordes", status: "estudar" },
  { id: 36, nome: "Si Maior", tipo: "Acordes", status: "estudar" },
  { id: 37, nome: "Fá # Maior", tipo: "Acordes", status: "estudar" },
  { id: 38, nome: "Dó # Maior", tipo: "Acordes", status: "estudar" },
  { id: 39, nome: "Fá Maior", tipo: "Acordes", status: "estudar" },
  { id: 40, nome: "Si b Maior", tipo: "Acordes", status: "estudar" },
  { id: 41, nome: "Mi b Maior", tipo: "Acordes", status: "estudar" },
  { id: 42, nome: "Lá b Maior", tipo: "Acordes", status: "estudar" },
  { id: 43, nome: "Ré b Maior", tipo: "Acordes", status: "estudar" },
  { id: 44, nome: "Sol b Maior", tipo: "Acordes", status: "estudar" },
  { id: 45, nome: "Dó b Maior", tipo: "Acordes", status: "estudar" },
  { id: 46, nome: "lá menor", tipo: "Acordes", status: "estudar" },
  { id: 47, nome: "mi menor", tipo: "Acordes", status: "estudar" },
  { id: 48, nome: "si menor", tipo: "Acordes", status: "estudar" },
  { id: 49, nome: "fá # menor", tipo: "Acordes", status: "estudar" },
  { id: 50, nome: "dó # menor", tipo: "Acordes", status: "estudar" },
  { id: 51, nome: "sol # menor", tipo: "Acordes", status: "estudar" },
  { id: 52, nome: "ré # menor", tipo: "Acordes", status: "estudar" },
  { id: 53, nome: "lá # menor", tipo: "Acordes", status: "estudar" },
  { id: 54, nome: "ré menor", tipo: "Acordes", status: "estudar" },
  { id: 55, nome: "sol menor", tipo: "Acordes", status: "estudar" },
  { id: 56, nome: "dó menor", tipo: "Acordes", status: "estudar" },
  { id: 57, nome: "fá menor", tipo: "Acordes", status: "estudar" },
  { id: 58, nome: "si b menor", tipo: "Acordes", status: "estudar" },
  { id: 59, nome: "mi b menor", tipo: "Acordes", status: "estudar" },
  { id: 60, nome: "lá b menor", tipo: "Acordes", status: "estudar" },
  { id: 61, nome: "Escala Cromática", tipo: "Cromática", status: "estudar" }
];
