export const morData = {
  "VOL 1": {
    "Estudos": [
      { id: 1, titulo: "MOR VOL. 1 Estudos 1", status: "estudar" },
      { id: 2, titulo: "MOR VOL. 1 Estudos 2", status: "estudar" },
      { id: 3, titulo: "MOR VOL. 1 Estudos 3", status: "estudar" },
      { id: 4, titulo: "MOR VOL. 1 Estudos 4", status: "estudar" },
      { id: 5, titulo: "MOR VOL. 1 Estudos 5", status: "estudar" },
      { id: 6, titulo: "MOR VOL. 1 Estudos 6", status: "estudar" },
      { id: 7, titulo: "MOR VOL. 1 Estudos 7", status: "estudar" },
      { id: 8, titulo: "MOR VOL. 1 Estudos 8", status: "estudar" },
      { id: 9, titulo: "MOR VOL. 1 Estudos 9", status: "estudar" },
      { id: 10, titulo: "MOR VOL. 1 Estudos 10", status: "estudar" },
      { id: 11, titulo: "MOR VOL. 1 Estudos 11", status: "estudar" },
      { id: 12, titulo: "MOR VOL. 1 Estudos 12", status: "estudar" },
      { id: 13, titulo: "MOR VOL. 1 Estudos 13", status: "estudar" },
      { id: 14, titulo: "MOR VOL. 1 Estudos 14", status: "estudar" },
      { id: 15, titulo: "MOR VOL. 1 Estudos 15", status: "estudar" },
      { id: 16, titulo: "MOR VOL. 1 Estudos 16", status: "estudar" },
      { id: 17, titulo: "MOR VOL. 1 Estudos 17", status: "estudar" },
      { id: 18, titulo: "MOR VOL. 1 Estudos 18", status: "estudar" },
      { id: 19, titulo: "MOR VOL. 1 Estudos 19", status: "estudar" },
      { id: 20, titulo: "MOR VOL. 1 Estudos 20", status: "estudar" },
      { id: 21, titulo: "MOR VOL. 1 Estudos 21", status: "estudar" },
      { id: 22, titulo: "MOR VOL. 1 Estudos 22", status: "estudar" },
      { id: 23, titulo: "MOR VOL. 1 Estudos 23", status: "estudar" },
      { id: 24, titulo: "MOR VOL. 1 Estudos 24", status: "estudar" },
      { id: 25, titulo: "MOR VOL. 1 Estudos 25", status: "estudar" },
      { id: 26, titulo: "MOR VOL. 1 Estudos 26", status: "estudar" },
      { id: 27, titulo: "MOR VOL. 1 Estudos 27", status: "estudar" },
      { id: 28, titulo: "MOR VOL. 1 Estudos 28", status: "estudar" },
      { id: 29, titulo: "MOR VOL. 1 Estudos 29", status: "estudar" },
      { id: 30, titulo: "MOR VOL. 1 Estudos 30", status: "estudar" },
      { id: 31, titulo: "MOR VOL. 1 Estudos 31", status: "estudar" },
      { id: 32, titulo: "MOR VOL. 1 Estudos 32", status: "estudar" },
      { id: 33, titulo: "MOR VOL. 1 Estudos 33", status: "estudar" },
      { id: 34, titulo: "MOR VOL. 1 Estudos 34", status: "estudar" },
      { id: 35, titulo: "MOR VOL. 1 Estudos 35", status: "estudar" },
      { id: 36, titulo: "MOR VOL. 1 Estudos 36", status: "estudar" },
      { id: 37, titulo: "MOR VOL. 1 Estudos 37", status: "estudar" },
      { id: 38, titulo: "MOR VOL. 1 Estudos 38", status: "estudar" },
      { id: 39, titulo: "MOR VOL. 1 Estudos 39", status: "estudar" },
      { id: 40, titulo: "MOR VOL. 1 Estudos 40", status: "estudar" }
    ],
    "Exercício": [
      { id: 41, titulo: "MOR VOL. 1 Exercício 1", status: "estudar" },
      { id: 42, titulo: "MOR VOL. 1 Exercício 2", status: "estudar" },
      { id: 43, titulo: "MOR VOL. 1 Exercício 3", status: "estudar" },
      { id: 44, titulo: "MOR VOL. 1 Exercício 4", status: "estudar" },
      { id: 45, titulo: "MOR VOL. 1 Exercício 5", status: "estudar" },
      { id: 46, titulo: "MOR VOL. 1 Exercício 6", status: "estudar" },
      { id: 47, titulo: "MOR VOL. 1 Exercício 7", status: "estudar" },
      { id: 48, titulo: "MOR VOL. 1 Exercício 8", status: "estudar" },
      { id: 49, titulo: "MOR VOL. 1 Exercício 9", status: "estudar" },
      { id: 50, titulo: "MOR VOL. 1 Exercício 10", status: "estudar" },
      { id: 51, titulo: "MOR VOL. 1 Exercício 11", status: "estudar" },
      { id: 52, titulo: "MOR VOL. 1 Exercício 12", status: "estudar" },
      { id: 53, titulo: "MOR VOL. 1 Exercício 13", status: "estudar" },
      { id: 54, titulo: "MOR VOL. 1 Exercício 14", status: "estudar" },
      { id: 55, titulo: "MOR VOL. 1 Exercício 15", status: "estudar" },
      { id: 56, titulo: "MOR VOL. 1 Exercício 16", status: "estudar" },
      { id: 57, titulo: "MOR VOL. 1 Exercício 17", status: "estudar" },
      { id: 58, titulo: "MOR VOL. 1 Exercício 18", status: "estudar" },
      { id: 59, titulo: "MOR VOL. 1 Exercício 19", status: "estudar" },
      { id: 60, titulo: "MOR VOL. 1 Exercício 20", status: "estudar" },
      { id: 61, titulo: "MOR VOL. 1 Exercício 21", status: "estudar" },
      { id: 62, titulo: "MOR VOL. 1 Exercício 22", status: "estudar" }
    ],
    "Exer pedal": [
      { id: 63, titulo: "MOR VOL. 1 Exer. Pedal 1", status: "estudar" },
      { id: 64, titulo: "MOR VOL. 1 Exer. Pedal 2", status: "estudar" },
      { id: 65, titulo: "MOR VOL. 1 Exer. Pedal 3", status: "estudar" }
    ],
    "Hinos": [
      { id: 66, titulo: "MOR VOL. 1 Hinos 158", status: "estudar" },
      { id: 67, titulo: "MOR VOL. 1 Hinos 131", status: "estudar" },
      { id: 68, titulo: "MOR VOL. 1 Hinos 468", status: "estudar" }
    ]
  },
  "VOL 2": {
    "Estudos": [
      { id: 69, titulo: "MOR VOL. 2 Estudos 1", status: "estudar" },
      { id: 70, titulo: "MOR VOL. 2 Estudos 2", status: "estudar" },
      { id: 71, titulo: "MOR VOL. 2 Estudos 3", status: "estudar" },
      { id: 72, titulo: "MOR VOL. 2 Estudos 4", status: "estudar" },
      { id: 73, titulo: "MOR VOL. 2 Estudos 5", status: "estudar" },
      { id: 74, titulo: "MOR VOL. 2 Estudos 6", status: "estudar" },
      { id: 75, titulo: "MOR VOL. 2 Estudos 7", status: "estudar" },
      { id: 76, titulo: "MOR VOL. 2 Estudos 8", status: "estudar" },
      { id: 77, titulo: "MOR VOL. 2 Estudos 9", status: "estudar" },
      { id: 78, titulo: "MOR VOL. 2 Estudos 10", status: "estudar" },
      { id: 79, titulo: "MOR VOL. 2 Estudos 11", status: "estudar" },
      { id: 80, titulo: "MOR VOL. 2 Estudos 12", status: "estudar" },
      { id: 81, titulo: "MOR VOL. 2 Estudos 13", status: "estudar" },
      { id: 82, titulo: "MOR VOL. 2 Estudos 14", status: "estudar" },
      { id: 83, titulo: "MOR VOL. 2 Estudos 15", status: "estudar" },
      { id: 84, titulo: "MOR VOL. 2 Estudos 16", status: "estudar" },
      { id: 85, titulo: "MOR VOL. 2 Estudos 17", status: "estudar" },
      { id: 86, titulo: "MOR VOL. 2 Estudos 18", status: "estudar" },
      { id: 87, titulo: "MOR VOL. 2 Estudos 19", status: "estudar" },
      { id: 88, titulo: "MOR VOL. 2 Estudos 20", status: "estudar" },
      { id: 89, titulo: "MOR VOL. 2 Estudos 21", status: "estudar" },
      { id: 90, titulo: "MOR VOL. 2 Estudos 22", status: "estudar" },
      { id: 91, titulo: "MOR VOL. 2 Estudos 23", status: "estudar" },
      { id: 92, titulo: "MOR VOL. 2 Estudos 24", status: "estudar" },
      { id: 93, titulo: "MOR VOL. 2 Estudos 25", status: "estudar" },
      { id: 94, titulo: "MOR VOL. 2 Estudos 26", status: "estudar" },
      { id: 95, titulo: "MOR VOL. 2 Estudos 27", status: "estudar" },
      { id: 96, titulo: "MOR VOL. 2 Estudos 28", status: "estudar" },
      { id: 97, titulo: "MOR VOL. 2 Estudos 29", status: "estudar" },
      { id: 98, titulo: "MOR VOL. 2 Estudos 30", status: "estudar" }
    ],
    "Exercício": [
      { id: 99, titulo: "MOR VOL. 2 Exercício 1", status: "estudar" },
      { id: 100, titulo: "MOR VOL. 2 Exercício 2", status: "estudar" },
      { id: 101, titulo: "MOR VOL. 2 Exercício 3", status: "estudar" },
      { id: 102, titulo: "MOR VOL. 2 Exercício 4", status: "estudar" },
      { id: 103, titulo: "MOR VOL. 2 Exercício 5", status: "estudar" },
      { id: 104, titulo: "MOR VOL. 2 Exercício 6", status: "estudar" },
      { id: 105, titulo: "MOR VOL. 2 Exercício 7", status: "estudar" },
      { id: 106, titulo: "MOR VOL. 2 Exercício 8", status: "estudar" },
      { id: 107, titulo: "MOR VOL. 2 Exercício 9", status: "estudar" },
      { id: 108, titulo: "MOR VOL. 2 Exercício 10", status: "estudar" },
      { id: 109, titulo: "MOR VOL. 2 Exercício 11", status: "estudar" },
      { id: 110, titulo: "MOR VOL. 2 Exercício 12", status: "estudar" },
      { id: 111, titulo: "MOR VOL. 2 Exercício 13", status: "estudar" },
      { id: 112, titulo: "MOR VOL. 2 Exercício 14", status: "estudar" },
      { id: 113, titulo: "MOR VOL. 2 Exercício 15", status: "estudar" },
      { id: 114, titulo: "MOR VOL. 2 Exercício 16", status: "estudar" },
      { id: 115, titulo: "MOR VOL. 2 Exercício 17", status: "estudar" },
      { id: 116, titulo: "MOR VOL. 2 Exercício 18", status: "estudar" },
      { id: 117, titulo: "MOR VOL. 2 Exercício 19", status: "estudar" },
      { id: 118, titulo: "MOR VOL. 2 Exercício 20", status: "estudar" }
    ],
    "Exer pedal": [
      { id: 119, titulo: "MOR VOL. 2 Exer. Pedal 1", status: "estudar" },
      { id: 120, titulo: "MOR VOL. 2 Exer. Pedal 2", status: "estudar" },
      { id: 121, titulo: "MOR VOL. 2 Exer. Pedal 3", status: "estudar" },
      { id: 122, titulo: "MOR VOL. 2 Exer. Pedal 4", status: "estudar" },
      { id: 123, titulo: "MOR VOL. 2 Exer. Pedal 5", status: "estudar" },
      { id: 124, titulo: "MOR VOL. 2 Exer. Pedal 6", status: "estudar" },
      { id: 125, titulo: "MOR VOL. 2 Exer. Pedal 7", status: "estudar" },
      { id: 126, titulo: "MOR VOL. 2 Exer. Pedal 8", status: "estudar" },
      { id: 127, titulo: "MOR VOL. 2 Exer. Pedal 9", status: "estudar" },
      { id: 128, titulo: "MOR VOL. 2 Exer. Pedal 10", status: "estudar" },
      { id: 129, titulo: "MOR VOL. 2 Exer. Pedal 11", status: "estudar" },
      { id: 130, titulo: "MOR VOL. 2 Exer. Pedal 12", status: "estudar" },
      { id: 131, titulo: "MOR VOL. 2 Exer. Pedal 13", status: "estudar" },
      { id: 132, titulo: "MOR VOL. 2 Exer. Pedal 14", status: "estudar" },
      { id: 133, titulo: "MOR VOL. 2 Exer. Pedal 15", status: "estudar" },
      { id: 134, titulo: "MOR VOL. 2 Exer. Pedal 16", status: "estudar" },
      { id: 135, titulo: "MOR VOL. 2 Exer. Pedal 17", status: "estudar" },
      { id: 136, titulo: "MOR VOL. 2 Exer. Pedal 18", status: "estudar" },
      { id: 137, titulo: "MOR VOL. 2 Exer. Pedal 19", status: "estudar" },
      { id: 138, titulo: "MOR VOL. 2 Exer. Pedal 20", status: "estudar" },
      { id: 139, titulo: "MOR VOL. 2 Exer. Pedal 21", status: "estudar" },
      { id: 140, titulo: "MOR VOL. 2 Exer. Pedal 22", status: "estudar" },
      { id: 141, titulo: "MOR VOL. 2 Exer. Pedal 23", status: "estudar" },
      { id: 142, titulo: "MOR VOL. 2 Exer. Pedal 24", status: "estudar" },
      { id: 143, titulo: "MOR VOL. 2 Exer. Pedal 25", status: "estudar" },
      { id: 144, titulo: "MOR VOL. 2 Exer. Pedal 26", status: "estudar" },
      { id: 145, titulo: "MOR VOL. 2 Exer. Pedal 27", status: "estudar" },
      { id: 146, titulo: "MOR VOL. 2 Exer. Pedal 28", status: "estudar" },
      { id: 147, titulo: "MOR VOL. 2 Exer. Pedal 29", status: "estudar" },
      { id: 148, titulo: "MOR VOL. 2 Exer. Pedal 30", status: "estudar" },
      { id: 149, titulo: "MOR VOL. 2 Exer. Pedal 31", status: "estudar" },
      { id: 150, titulo: "MOR VOL. 2 Exer. Pedal 32", status: "estudar" },
      { id: 151, titulo: "MOR VOL. 2 Exer. Pedal 33", status: "estudar" },
      { id: 152, titulo: "MOR VOL. 2 Exer. Pedal 34", status: "estudar" },
      { id: 153, titulo: "MOR VOL. 2 Exer. Pedal 35", status: "estudar" },
      { id: 154, titulo: "MOR VOL. 2 Exer. Pedal 36", status: "estudar" },
      { id: 155, titulo: "MOR VOL. 2 Exer. Pedal 37", status: "estudar" },
      { id: 156, titulo: "MOR VOL. 2 Exer. Pedal 38", status: "estudar" },
      { id: 157, titulo: "MOR VOL. 2 Exer. Pedal 39", status: "estudar" },
      { id: 158, titulo: "MOR VOL. 2 Exer. Pedal 40", status: "estudar" },
      { id: 159, titulo: "MOR VOL. 2 Exer. Pedal 41", status: "estudar" },
      { id: 160, titulo: "MOR VOL. 2 Exer. Pedal 42", status: "estudar" },
      { id: 161, titulo: "MOR VOL. 2 Exer. Pedal 43", status: "estudar" },
      { id: 162, titulo: "MOR VOL. 2 Exer. Pedal 44", status: "estudar" },
      { id: 163, titulo: "MOR VOL. 2 Exer. Pedal 45", status: "estudar" },
      { id: 164, titulo: "MOR VOL. 2 Exer. Pedal 46", status: "estudar" },
      { id: 165, titulo: "MOR VOL. 2 Exer. Pedal 47", status: "estudar" },
      { id: 166, titulo: "MOR VOL. 2 Exer. Pedal 48", status: "estudar" },
      { id: 167, titulo: "MOR VOL. 2 Exer. Pedal 49", status: "estudar" },
      { id: 168, titulo: "MOR VOL. 2 Exer. Pedal 50", status: "estudar" }
    ],
    "Escalas": [
      { id: 169, titulo: "MOR VOL. 2 Escala Cromática", status: "estudar" },
      { id: 170, titulo: "MOR VOL. 2 Escala Sol M", status: "estudar" },
      { id: 171, titulo: "MOR VOL. 2 Escala Ré M", status: "estudar" },
      { id: 172, titulo: "MOR VOL. 2 Escala Lá M", status: "estudar" },
      { id: 173, titulo: "MOR VOL. 2 Escala Mi M", status: "estudar" },
      { id: 174, titulo: "MOR VOL. 2 Escala Si M", status: "estudar" },
      { id: 175, titulo: "MOR VOL. 2 Escala Fá# M", status: "estudar" },
      { id: 176, titulo: "MOR VOL. 2 Escala Dó# M", status: "estudar" },
      { id: 177, titulo: "MOR VOL. 2 Escala Fá M", status: "estudar" },
      { id: 178, titulo: "MOR VOL. 2 Escala Sib M", status: "estudar" },
      { id: 179, titulo: "MOR VOL. 2 Escala Mib M", status: "estudar" },
      { id: 180, titulo: "MOR VOL. 2 Escala Lab M", status: "estudar" },
      { id: 181, titulo: "MOR VOL. 2 Escala Reb M", status: "estudar" },
      { id: 182, titulo: "MOR VOL. 2 Escala Solb M", status: "estudar" },
      { id: 183, titulo: "MOR VOL. 2 Escala Dob M", status: "estudar" }
    ]
  },
  "VOL 3": {
    "Estudos": [
      { id: 184, titulo: "MOR VOL. 3 Estudos 1", status: "estudar" },
      { id: 185, titulo: "MOR VOL. 3 Estudos 2", status: "estudar" },
      { id: 186, titulo: "MOR VOL. 3 Estudos 3", status: "estudar" },
      { id: 187, titulo: "MOR VOL. 3 Estudos 4", status: "estudar" },
      { id: 188, titulo: "MOR VOL. 3 Estudos 5", status: "estudar" },
      { id: 189, titulo: "MOR VOL. 3 Estudos 6", status: "estudar" },
      { id: 190, titulo: "MOR VOL. 3 Estudos 7", status: "estudar" },
      { id: 191, titulo: "MOR VOL. 3 Estudos 8", status: "estudar" },
      { id: 192, titulo: "MOR VOL. 3 Estudos 9", status: "estudar" },
      { id: 193, titulo: "MOR VOL. 3 Estudos 10", status: "estudar" },
      { id: 194, titulo: "MOR VOL. 3 Estudos 11", status: "estudar" },
      { id: 195, titulo: "MOR VOL. 3 Estudos 12", status: "estudar" },
      { id: 196, titulo: "MOR VOL. 3 Estudos 13", status: "estudar" },
            { id: 197, titulo: "MOR VOL. 3 Estudos 14", status: "estudar" },
      { id: 198, titulo: "MOR VOL. 3 Estudos 15", status: "estudar" },
      { id: 199, titulo: "MOR VOL. 3 Estudos 16", status: "estudar" },
      { id: 200, titulo: "MOR VOL. 3 Estudos 17", status: "estudar" },
      { id: 201, titulo: "MOR VOL. 3 Estudos 18", status: "estudar" },
      { id: 202, titulo: "MOR VOL. 3 Estudos 19", status: "estudar" },
      { id: 203, titulo: "MOR VOL. 3 Estudos 20", status: "estudar" },
      { id: 204, titulo: "MOR VOL. 3 Estudos 21", status: "estudar" },
      { id: 205, titulo: "MOR VOL. 3 Estudos 22", status: "estudar" },
      { id: 206, titulo: "MOR VOL. 3 Estudos 23", status: "estudar" },
      { id: 207, titulo: "MOR VOL. 3 Estudos 24", status: "estudar" },
      { id: 208, titulo: "MOR VOL. 3 Estudos 25", status: "estudar" }
    ],
    "Exercício": [
      { id: 209, titulo: "MOR VOL. 3 Exercício 1", status: "estudar" },
      { id: 210, titulo: "MOR VOL. 3 Exercício 2", status: "estudar" },
      { id: 211, titulo: "MOR VOL. 3 Exercício 3", status: "estudar" },
      { id: 212, titulo: "MOR VOL. 3 Exercício 4", status: "estudar" },
      { id: 213, titulo: "MOR VOL. 3 Exercício 5", status: "estudar" },
      { id: 214, titulo: "MOR VOL. 3 Exercício 6", status: "estudar" },
      { id: 215, titulo: "MOR VOL. 3 Exercício 7", status: "estudar" },
      { id: 216, titulo: "MOR VOL. 3 Exercício 8", status: "estudar" },
      { id: 217, titulo: "MOR VOL. 3 Exercício 9", status: "estudar" },
      { id: 218, titulo: "MOR VOL. 3 Exercício 10", status: "estudar" }
    ],
    "Hinos": [
      { id: 219, titulo: "MOR VOL. 3 Hinos 211", status: "estudar" },
      { id: 220, titulo: "MOR VOL. 3 Hinos 416", status: "estudar" },
      { id: 221, titulo: "MOR VOL. 3 Hinos 399", status: "estudar" },
      { id: 222, titulo: "MOR VOL. 3 Hinos 402", status: "estudar" },
      { id: 223, titulo: "MOR VOL. 3 Hinos 12", status: "estudar" },
      { id: 224, titulo: "MOR VOL. 3 Hinos 103", status: "estudar" },
      { id: 225, titulo: "MOR VOL. 3 Hinos 63", status: "estudar" },
      { id: 226, titulo: "MOR VOL. 3 Hinos 310", status: "estudar" },
      { id: 227, titulo: "MOR VOL. 3 Hinos 239", status: "estudar" },
      { id: 228, titulo: "MOR VOL. 3 Hinos 295", status: "estudar" },
      { id: 229, titulo: "MOR VOL. 3 Hinos 35", status: "estudar" },
      { id: 230, titulo: "MOR VOL. 3 Hinos 76", status: "estudar" },
      { id: 231, titulo: "MOR VOL. 3 Hinos 185", status: "estudar" },
      { id: 232, titulo: "MOR VOL. 3 Hinos 320", status: "estudar" },
      { id: 233, titulo: "MOR VOL. 3 Hinos 25", status: "estudar" },
      { id: 234, titulo: "MOR VOL. 3 Hinos 101", status: "estudar" },
      { id: 235, titulo: "MOR VOL. 3 Hinos 368", status: "estudar" },
      { id: 236, titulo: "MOR VOL. 3 Hinos 372", status: "estudar" },
      { id: 237, titulo: "MOR VOL. 3 Hinos 298", status: "estudar" },
      { id: 238, titulo: "MOR VOL. 3 Hinos 377", status: "estudar" }
    ]
  }
};